import = ["/home/zzzpx0/.config/alacritty/dracula.toml"]

[font]
size = 12.0

[font.normal]
family = "TerminessTTF NF"
style = "Medium"

[window]
decorations = "none"
opacity = 0.9

[window.padding]
x = 10
y = 10
