
[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.normal]
family = "BigBlueTermPlus Nerd Font Propo"

[window]
decorations = "none"
opacity = 0.9

[window.padding]
x = 10
y = 10

[general]
import = ["~/.config/alacritty/catppuccin-mocha.toml"]
